### ISSUE TITLE
エラーMSG インストール時に "npm ERR! missing script: install" w/macOS

### ISSUE THREAD

**Issue by KEINOS** [hidao80/TsumiQiita#14]
## 環境

macOS HighSierra（OSX 10.13.4）を使っています。`node` は v9.11.1 で `npm` は v5.6.0です。独身です。

## 現象

[INSTALL.md](https://github.com/hidao80/TsumiQiita/blob/master/INSTALL.md#macos-1013) の手順でインストールをしたところ、`$ npm run install` のステップで「`npm ERR! missing script: install`」エラーが発生します。

https://stackoverflow.com/questions/31976722/start-script-missing-error-when-running-npm-start

上記 [StackOverflow の内容](https://stackoverflow.com/questions/31976722/start-script-missing-error-when-running-npm-start)とエラーが似ているのですが、「[`package.json`](https://github.com/hidao80/TsumiQiita/blob/master/src/package.json)に `install` （記事では `start`）の記述が抜けているから」とありますが、記述がなくても動いているアプリもあるようです。

何かあらかじめ初期化などをする必要があるのでしょうか？

## 実行ログ

```20180406_05.sh-session
$ node --version
v9.11.1
$
$ npm --version
5.6.0
$
$ cd /Path/To/GitHub/Fork_TsumiQiita/src
$
$ ls
css			js			scss
index.html		package-lock.json
index.js		package.json
$
$ npm run install
npm ERR! missing script: install

npm ERR! A complete log of this run can be found in:
npm ERR! ~/.npm/_logs/2018-04-05T20_48_18_464Z-debug.log
$
$ cat ~/.npm/_logs/2018-04-05T20_48_18_464Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'install' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose stack Error: missing script: install
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:402:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:357:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:400:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)
5 verbose cwd /Path/To/GitHub/Fork_TsumiQiita/src
6 verbose Darwin 17.5.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "install"
8 verbose node v9.11.1
9 verbose npm  v5.6.0
10 error missing script: install
11 verbose exit [ 1, true ]
$ 
```

**Comment by hidao80** [comment]
これは失礼しました！
インストールコマンドの記載ミスです。

`npm run install`ではなく`npm install`として実行してください！
INSTALL.mdも修正しました。🙇‍♂️

**Comment by KEINOS** [comment]
ﾂﾐｷﾀ━━━(ﾟ(ﾟ∀(ﾟ∀ﾟ(☆∀☆)ﾟ∀ﾟ)∀ﾟ)ﾟ)━━━!!

```20180406_0749.sh-session
$ npm install

> node-sass@4.8.3 install /Path/To/GitHub/Fork_TsumiQiita/src/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/darwin-x64-59_binding.node
Download complete ░⸩ ⠋ :
Binary saved to /Path/To/GitHub/Fork_TsumiQiita/src/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Caching binary to ~/.npm/node-sass/4.8.3/darwin-x64-59_binding.node

> electron@1.8.4 postinstall /Path/To/GitHub/Fork_TsumiQiita/src/node_modules/electron
> node install.js

Downloading SHASUMS256.txt
[============================================>] 100.0% of 3.43 kB (3.43 kB/s)

> node-sass@4.8.3 postinstall /Path/To/GitHub/Fork_TsumiQiita/src/node_modules/node-sass
> node scripts/build.js

Binary found at /Path/To/GitHub/Fork_TsumiQiita/src/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine
added 334 packages in 111.068s
$
$ npm run build-mac

> TsumiQiita@0.1.0 build-mac /Path/To/GitHub/Fork_TsumiQiita/src
> electron-packager . TsumiQiita --out=../build --pratform=darwin --arch=x64 --overwrite --asar

Packaging app for platform darwin x64 using electron v1.8.4
Wrote new app to ../build/TsumiQiita-darwin-x64
$
$ cd ../build/TsumiQiita-darwin-x64
$ ls
LICENSE			TsumiQiita.app
LICENSES.chromium.html	version
$
$ open ./TsumiQiita.app
```
<kbd><img width="100%" alt="2018-04-06 7 54 06 _1200x" src="https://user-images.githubusercontent.com/11840938/38395847-ea1d4f02-396f-11e8-862f-1c00482b2174.png"></kbd>
